name: Nebula deploy
on:
    push:
        branches:
            - main
        paths:
            - "nebula/**"

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    deploy_to_production:
        name: Deploying to production
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./nebula
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup flyctl
              uses: superfly/flyctl-actions/setup-flyctl@master

            - name: Deploy to production
              run: flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.NEBULA_FLY_DEPLOYMENT_PROD }}
